### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by cstmth** [churchstudio-org/super_scaffold#1]
This is the Scaffold I was looking for. It is sad that it is displayed so far below other, worse scaffolds. Maybe consider getting all PUB points to improve that.

Other than that, thank you for Super Scaffold!

**Comment by lucaslannes** [comment]
Thank you, @carldressler! Your feedback is very important to me, since the Super Scaffold is my first contribution to the open source community 😄

I'll work to improve the score of the package 👍
