### ISSUE TITLE
[Bug] Rotating the screen causes drawer icon to disappear

### ISSUE THREAD

**Issue by nwparker** [churchstudio-org/super_scaffold#2]
On a tablet, rotating the screen will cause the upper left drawer icon to disappear

**Comment by lucaslannes** [comment]
@nwparker, thanks for open this issue 😄

I believe that I developed this as a default behaviour.

So do you want to be able to click on the drawer icon to close/open the drawer even in landscape mode?

**Comment by nwparker** [comment]
Not quite what I meant.

It's that the drawer icon will literally disappear

I attempted to do a screen recording. But on the example app, I cannot recreate the issue. So I assume this is actually an issue somewhere on my end. Sorry about that.

You can close this if you'd like. I'll re-open this if I can re-create the issues on the example project.

**Comment by lucaslannes** [comment]
@nwparker, below is a snippet of the example app, [check this out](https://github.com/lucaslannes/super_scaffold/blob/main/example/lib/main.dart#L62):

![image](https://user-images.githubusercontent.com/54950765/130335119-aba549b3-8492-49fa-9463-0ddb4dbf8dca.png)

On line 62, I'm hiding/showing the drawer icon based on screen current rotation.

But this is not the default behaviour of SuperScaffold, I have implemented this just for the example app.

Let me know if you are talking about this, please 😄

**Comment by nwparker** [comment]
> @nwparker, below is a snippet of the example app, [check this out](https://github.com/lucaslannes/super_scaffold/blob/main/example/lib/main.dart#L62):
> 
> ![image](https://user-images.githubusercontent.com/54950765/130335119-aba549b3-8492-49fa-9463-0ddb4dbf8dca.png)
> 
> On line 62, I'm hiding/showing the drawer icon based on screen current rotation.
> 
> But this is not the default behaviour of SuperScaffold, I have implemented this just for the example app.
> 
> Let me know if you are talking about this, please 😄

Ah, awesome! That's exactly what I needed. Thanks for linking the code snippet 😁

**Comment by lucaslannes** [comment]
Do you think it makes sense to create a SuperAppBar widget to handle this scenario? 🤔

So the SuperAppBar will hide the drawer icon automatically if the device is in landscape mode.

**Comment by nwparker** [comment]
> Do you think it makes sense to create a SuperAppBar widget to handle this scenario? 🤔
> 
> So the SuperAppBar will hide the drawer icon automatically if the device is in landscape mode.

Hmmm, I personally think it makes sense for the package to handle this scenario.

**Comment by lucaslannes** [comment]
Great, @nwparker, I'll work on this new widget 😄

**Comment by lucaslannes** [comment]
@nwparker, now you can check this feature on the version 0.0.3 🚀

Thanks for the suggestion, God bless you 😄
